providers = ["node", "python"]

[variables]
NODE_VERSION = "20.x"
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmd = "npm ci --legacy-peer-deps || npm install --legacy-peer-deps"

[phases.build] 
cmd = "npm run build && pip install -r requirements.txt"

[start]
cmd = "npm start"
